import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'history',
    'certifications',
    'projects',
    {
      type: 'category',
      label: 'Experiences',
      link: {
        type: 'doc',
        id: 'experiences/index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'experiences/screen-ict',
        },
      ],
    },
  ],
};

export default sidebars;
